#run-base image

# Define the base image

FROM public.ecr.aws/initializ/builder/run-base:latest

# Set required CNB target information
LABEL io.buildpacks.base.distro.name="busybox"
LABEL io.buildpacks.base.distro.version="1.36.1"

LABEL io.buildpacks.stack.id="Initializ Distroless Stack"

ENV CNB_STACK_ID="Initializ Distroless Stack"
